import os
import re
import json

BASE_DIR = r"C:\Users\DYNABOOK\.gemini\antigravity\scratch\neon-site"
VERCEL_JSON_PATH = os.path.join(BASE_DIR, "vercel.json")

broken_links_list = [
    "https://neonautotransport.com/alabama-car-shipping/birmingham/",
    "https://neonautotransport.com/alabama-car-shipping/huntsville/",
    "https://neonautotransport.com/alabama-car-shipping/mobile/",
    "https://neonautotransport.com/alabama-car-shipping/montgomery/",
    "https://neonautotransport.com/alaska-car-shipping/anchorage/",
    "https://neonautotransport.com/alaska-car-shipping/fairbanks/",
    "https://neonautotransport.com/alaska-car-shipping/juneau/",
    "https://neonautotransport.com/alaska-car-shipping/sitka/",
    "https://neonautotransport.com/arizona-car-shipping/chandler/",
    "https://neonautotransport.com/arizona-car-shipping/mesa/",
    "https://neonautotransport.com/arizona-car-shipping/phoenix/",
    "https://neonautotransport.com/arizona-car-shipping/tucson/",
    "https://neonautotransport.com/arkansas-car-shipping/fayetteville/",
    "https://neonautotransport.com/arkansas-car-shipping/fort-smith/",
    "https://neonautotransport.com/arkansas-car-shipping/little-rock/",
    "https://neonautotransport.com/arkansas-car-shipping/springdale/",
    "https://neonautotransport.com/california-car-shipping/fresno/",
    "https://neonautotransport.com/california-car-shipping/houston-tx-to-los-angeles/",
    "https://neonautotransport.com/california-car-shipping/los-angeles/",
    "https://neonautotransport.com/california-car-shipping/new-york-city-ny-to-los-angeles/",
    "https://neonautotransport.com/california-car-shipping/san-diego/",
    "https://neonautotransport.com/california-car-shipping/san-francisco-ca-to-los-angeles/",
    "https://neonautotransport.com/california-car-shipping/san-francisco/",
    "https://neonautotransport.com/california-car-shipping/san-jose/",
    "https://neonautotransport.com/colorado-car-shipping/aurora/",
    "https://neonautotransport.com/colorado-car-shipping/austin-tx-to-denver/",
    "https://neonautotransport.com/colorado-car-shipping/colorado-springs/",
    "https://neonautotransport.com/colorado-car-shipping/denver/",
    "https://neonautotransport.com/colorado-car-shipping/fort-collins/",
    "https://neonautotransport.com/colorado-car-shipping/las-vegas-nv-to-denver/",
    "https://neonautotransport.com/colorado-car-shipping/phoenix-az-to-denver/",
    "https://neonautotransport.com/connecticut-car-shipping/bridgeport/",
    "https://neonautotransport.com/connecticut-car-shipping/hartford/",
    "https://neonautotransport.com/connecticut-car-shipping/new-haven/",
    "https://neonautotransport.com/connecticut-car-shipping/stamford/",
    "https://neonautotransport.com/delaware-car-shipping/dover/",
    "https://neonautotransport.com/delaware-car-shipping/middletown/",
    "https://neonautotransport.com/delaware-car-shipping/newark/",
    "https://neonautotransport.com/delaware-car-shipping/wilmington/",
    "https://neonautotransport.com/florida-car-shipping/atlanta-ga-to-miami/",
    "https://neonautotransport.com/florida-car-shipping/boston-ma-to-miami/",
    "https://neonautotransport.com/florida-car-shipping/jacksonville/",
    "https://neonautotransport.com/florida-car-shipping/philadelphia-pa-to-orlando/",
    "https://neonautotransport.com/florida-car-shipping/st-petersburg/",
    "https://neonautotransport.com/florida-car-shipping/tampa/",
    "https://neonautotransport.com/georgia-car-shipping/atlanta/",
    "https://neonautotransport.com/georgia-car-shipping/augusta/",
    "https://neonautotransport.com/georgia-car-shipping/chicago-il-to-atlanta/",
    "https://neonautotransport.com/georgia-car-shipping/columbus/",
    "https://neonautotransport.com/georgia-car-shipping/macon/",
    "https://neonautotransport.com/hawaii-car-shipping/hilo/",
    "https://neonautotransport.com/hawaii-car-shipping/honolulu/",
    "https://neonautotransport.com/hawaii-car-shipping/kailua/",
    "https://neonautotransport.com/hawaii-car-shipping/pearl-city/",
    "https://neonautotransport.com/idaho-car-shipping/boise/",
    "https://neonautotransport.com/idaho-car-shipping/idaho-falls/",
    "https://neonautotransport.com/idaho-car-shipping/meridian/",
    "https://neonautotransport.com/idaho-car-shipping/nampa/",
    "https://neonautotransport.com/illinois-car-shipping/aurora/",
    "https://neonautotransport.com/illinois-car-shipping/chicago/",
    "https://neonautotransport.com/illinois-car-shipping/joliet/",
    "https://neonautotransport.com/illinois-car-shipping/naperville/",
    "https://neonautotransport.com/illinois-car-shipping/tampa-fl-to-chicago/",
    "https://neonautotransport.com/indiana-car-shipping/evansville/",
    "https://neonautotransport.com/indiana-car-shipping/fort-wayne/",
    "https://neonautotransport.com/indiana-car-shipping/indianapolis/",
    "https://neonautotransport.com/indiana-car-shipping/south-bend/",
    "https://neonautotransport.com/iowa-car-shipping/cedar-rapids/",
    "https://neonautotransport.com/iowa-car-shipping/davenport/",
    "https://neonautotransport.com/iowa-car-shipping/des-moines/",
    "https://neonautotransport.com/iowa-car-shipping/sioux-city/",
    "https://neonautotransport.com/kansas-car-shipping/kansas-city/",
    "https://neonautotransport.com/kansas-car-shipping/olathe/",
    "https://neonautotransport.com/kansas-car-shipping/overland-park/",
    "https://neonautotransport.com/kansas-car-shipping/wichita/",
    "https://neonautotransport.com/kentucky-car-shipping/bowling-green/",
    "https://neonautotransport.com/kentucky-car-shipping/lexington/",
    "https://neonautotransport.com/kentucky-car-shipping/louisville/",
    "https://neonautotransport.com/kentucky-car-shipping/owensboro/",
    "https://neonautotransport.com/louisiana-car-shipping/baton-rouge/",
    "https://neonautotransport.com/louisiana-car-shipping/lafayette/",
    "https://neonautotransport.com/louisiana-car-shipping/new-orleans/",
    "https://neonautotransport.com/louisiana-car-shipping/shreveport/",
    "https://neonautotransport.com/maine-car-shipping/bangor/",
    "https://neonautotransport.com/maine-car-shipping/lewiston/",
    "https://neonautotransport.com/maine-car-shipping/portland/",
    "https://neonautotransport.com/maine-car-shipping/south-portland/",
    "https://neonautotransport.com/maryland-car-shipping/baltimore/",
    "https://neonautotransport.com/maryland-car-shipping/columbia/",
    "https://neonautotransport.com/maryland-car-shipping/germantown/",
    "https://neonautotransport.com/maryland-car-shipping/silver-spring/",
    "https://neonautotransport.com/massachusetts-car-shipping/boston/",
    "https://neonautotransport.com/massachusetts-car-shipping/cambridge/",
    "https://neonautotransport.com/massachusetts-car-shipping/springfield/",
    "https://neonautotransport.com/massachusetts-car-shipping/worcester/",
    "https://neonautotransport.com/michigan-car-shipping/detroit/",
    "https://neonautotransport.com/michigan-car-shipping/grand-rapids/",
    "https://neonautotransport.com/michigan-car-shipping/sterling-heights/",
    "https://neonautotransport.com/michigan-car-shipping/warren/",
    "https://neonautotransport.com/minnesota-car-shipping/duluth/",
    "https://neonautotransport.com/minnesota-car-shipping/minneapolis/",
    "https://neonautotransport.com/minnesota-car-shipping/rochester/",
    "https://neonautotransport.com/minnesota-car-shipping/st-paul/",
    "https://neonautotransport.com/mississippi-car-shipping/biloxi/",
    "https://neonautotransport.com/mississippi-car-shipping/gulfport/",
    "https://neonautotransport.com/mississippi-car-shipping/jackson/",
    "https://neonautotransport.com/mississippi-car-shipping/southaven/",
    "https://neonautotransport.com/missouri-car-shipping/columbia/",
    "https://neonautotransport.com/missouri-car-shipping/kansas-city/",
    "https://neonautotransport.com/missouri-car-shipping/springfield/",
    "https://neonautotransport.com/missouri-car-shipping/st-louis/",
    "https://neonautotransport.com/montana-car-shipping/billings/",
    "https://neonautotransport.com/montana-car-shipping/bozeman/",
    "https://neonautotransport.com/montana-car-shipping/great-falls/",
    "https://neonautotransport.com/montana-car-shipping/missoula/",
    "https://neonautotransport.com/nebraska-car-shipping/bellevue/",
    "https://neonautotransport.com/nebraska-car-shipping/grand-island/",
    "https://neonautotransport.com/nebraska-car-shipping/lincoln/",
    "https://neonautotransport.com/nebraska-car-shipping/omaha/",
    "https://neonautotransport.com/nevada-car-shipping/henderson/",
    "https://neonautotransport.com/nevada-car-shipping/las-vegas/",
    "https://neonautotransport.com/nevada-car-shipping/los-angeles-ca-to-las-vegas/",
    "https://neonautotransport.com/nevada-car-shipping/north-las-vegas/",
    "https://neonautotransport.com/nevada-car-shipping/reno/",
    "https://neonautotransport.com/new-hampshire-car-shipping/concord/",
    "https://neonautotransport.com/new-hampshire-car-shipping/derry/",
    "https://neonautotransport.com/new-hampshire-car-shipping/manchester/",
    "https://neonautotransport.com/new-hampshire-car-shipping/nashua/",
    "https://neonautotransport.com/new-jersey-car-shipping/elizabeth/",
    "https://neonautotransport.com/new-jersey-car-shipping/jersey-city/",
    "https://neonautotransport.com/new-jersey-car-shipping/newark/",
    "https://neonautotransport.com/new-jersey-car-shipping/orlando-fl-to-newark/",
    "https://neonautotransport.com/new-jersey-car-shipping/paterson/",
    "https://neonautotransport.com/new-mexico-car-shipping/albuquerque/",
    "https://neonautotransport.com/new-mexico-car-shipping/las-cruces/",
    "https://neonautotransport.com/new-mexico-car-shipping/rio-rancho/",
    "https://neonautotransport.com/new-mexico-car-shipping/santa-fe/",
    "https://neonautotransport.com/new-york-car-shipping/buffalo/",
    "https://neonautotransport.com/new-york-car-shipping/miami-fl-to-new-york-city/",
    "https://neonautotransport.com/new-york-car-shipping/new-york-city/",
    "https://neonautotransport.com/new-york-car-shipping/rochester/",
    "https://neonautotransport.com/new-york-car-shipping/syracuse/",
    "https://neonautotransport.com/new-york-car-shipping/yonkers/",
    "https://neonautotransport.com/north-carolina-car-shipping/charlotte/",
    "https://neonautotransport.com/north-carolina-car-shipping/durham/",
    "https://neonautotransport.com/north-carolina-car-shipping/greensboro/",
    "https://neonautotransport.com/north-carolina-car-shipping/raleigh/",
    "https://neonautotransport.com/north-dakota-car-shipping/bismarck/",
    "https://neonautotransport.com/north-dakota-car-shipping/fargo/",
    "https://neonautotransport.com/north-dakota-car-shipping/grand-forks/",
    "https://neonautotransport.com/north-dakota-car-shipping/minot/",
    "https://neonautotransport.com/ohio-car-shipping/cincinnati/",
    "https://neonautotransport.com/ohio-car-shipping/cleveland/",
    "https://neonautotransport.com/ohio-car-shipping/columbus/",
    "https://neonautotransport.com/ohio-car-shipping/toledo/",
    "https://neonautotransport.com/oklahoma-car-shipping/broken-arrow/",
    "https://neonautotransport.com/oklahoma-car-shipping/norman/",
    "https://neonautotransport.com/oklahoma-car-shipping/oklahoma-city/",
    "https://neonautotransport.com/oklahoma-car-shipping/tulsa/",
    "https://neonautotransport.com/oregon-car-shipping/eugene/",
    "https://neonautotransport.com/oregon-car-shipping/gresham/",
    "https://neonautotransport.com/oregon-car-shipping/portland/",
    "https://neonautotransport.com/oregon-car-shipping/salem/",
    "https://neonautotransport.com/pennsylvania-car-shipping/allentown/",
    "https://neonautotransport.com/pennsylvania-car-shipping/erie/",
    "https://neonautotransport.com/pennsylvania-car-shipping/philadelphia/",
    "https://neonautotransport.com/pennsylvania-car-shipping/pittsburgh/",
    "https://neonautotransport.com/rhode-island-car-shipping/cranston/",
    "https://neonautotransport.com/rhode-island-car-shipping/pawtucket/",
    "https://neonautotransport.com/rhode-island-car-shipping/providence/",
    "https://neonautotransport.com/rhode-island-car-shipping/warwick/",
    "https://neonautotransport.com/south-carolina-car-shipping/charleston/",
    "https://neonautotransport.com/south-carolina-car-shipping/columbia/",
    "https://neonautotransport.com/south-carolina-car-shipping/mount-pleasant/",
    "https://neonautotransport.com/south-carolina-car-shipping/north-charleston/",
    "https://neonautotransport.com/south-dakota-car-shipping/aberdeen/",
    "https://neonautotransport.com/south-dakota-car-shipping/brookings/",
    "https://neonautotransport.com/south-dakota-car-shipping/rapid-city/",
    "https://neonautotransport.com/south-dakota-car-shipping/sioux-falls/",
    "https://neonautotransport.com/tennessee-car-shipping/chattanooga/",
    "https://neonautotransport.com/tennessee-car-shipping/knoxville/",
    "https://neonautotransport.com/tennessee-car-shipping/memphis/",
    "https://neonautotransport.com/tennessee-car-shipping/nashville/",
    "https://neonautotransport.com/texas-car-shipping/chicago-il-to-dallas/",
    "https://neonautotransport.com/texas-car-shipping/dallas-tx-to-houston/",
    "https://neonautotransport.com/texas-car-shipping/detroit-mi-to-dallas/",
    "https://neonautotransport.com/utah-car-shipping/provo/",
    "https://neonautotransport.com/utah-car-shipping/salt-lake-city/",
    "https://neonautotransport.com/utah-car-shipping/west-jordan/",
    "https://neonautotransport.com/utah-car-shipping/west-valley-city/",
    "https://neonautotransport.com/vermont-car-shipping/barre/",
    "https://neonautotransport.com/vermont-car-shipping/burlington/",
    "https://neonautotransport.com/vermont-car-shipping/rutland/",
    "https://neonautotransport.com/vermont-car-shipping/south-burlington/",
    "https://neonautotransport.com/washington-car-shipping/san-diego-ca-to-seattle/",
    "https://neonautotransport.com/washington-car-shipping/seattle/",
    "https://neonautotransport.com/washington-car-shipping/spokane/",
    "https://neonautotransport.com/washington-car-shipping/tacoma/",
    "https://neonautotransport.com/washington-car-shipping/vancouver/",
    "https://neonautotransport.com/west-virginia-car-shipping/charleston/",
    "https://neonautotransport.com/west-virginia-car-shipping/huntington/",
    "https://neonautotransport.com/west-virginia-car-shipping/morgantown/",
    "https://neonautotransport.com/west-virginia-car-shipping/parkersburg/",
    "https://neonautotransport.com/wisconsin-car-shipping/green-bay/",
    "https://neonautotransport.com/wisconsin-car-shipping/kenosha/",
    "https://neonautotransport.com/wisconsin-car-shipping/madison/",
    "https://neonautotransport.com/wisconsin-car-shipping/milwaukee/",
    "https://neonautotransport.com/wyoming-car-shipping/casper/",
    "https://neonautotransport.com/wyoming-car-shipping/cheyenne/",
    "https://neonautotransport.com/wyoming-car-shipping/gillette/",
    "https://neonautotransport.com/wyoming-car-shipping/laramie/",
]

print(f"=== VERIFYING {len(broken_links_list)} BROKEN INTERNAL LINKS ===")

with open(VERCEL_JSON_PATH, "r", encoding="utf-8") as f:
    vdata = json.load(f)

redirect_sources = {r["source"] for r in vdata.get("redirects", [])}

missing_redirects = []
for full_url in broken_links_list:
    path = full_url.replace("https://neonautotransport.com", "")
    if path not in redirect_sources:
        missing_redirects.append(path)

print(f"Missing 301 redirects in vercel.json: {len(missing_redirects)}")

print("=== SEARCHING SITEWIDE FOR ANY REMAINING BROKEN HREF ATTRIBUTES ===")
found_broken_hrefs = 0
for root, dirs, files in os.walk(BASE_DIR):
    if any(ignore in root for ignore in [".git", "node_modules", ".agents", "scripts", "brain"]):
        continue
    for file in files:
        if file.endswith(".html"):
            fpath = os.path.join(root, file)
            with open(fpath, "r", encoding="utf-8", errors="ignore") as f:
                c = f.read()
            for full_url in broken_links_list:
                path = full_url.replace("https://neonautotransport.com", "")
                if f'href="{path}"' in c or f"href='{path}'" in c or f'href="{path[:-1]}"' in c:
                    found_broken_hrefs += 1
                    print(f"Broken href found in {file} -> {path}")

print(f"Verification Complete: Found {found_broken_hrefs} broken href links in HTML files.")
